# Generated by Django 5.2.6 on 2025-09-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
