# Generated by Django 5.2.6 on 2025-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_remove_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='add_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
